package ru.eltex.project.simpleappointer.entities;

import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * This entity class represents a Invite class that allows to
 * keep working with invite records in DB
 * @version 1.0
 * @author skwardlow
 * @see Entity
 * @see lombok.Setter
 * */
@lombok.Getter
@lombok.Setter
@Entity
@NoArgsConstructor
public class Invite {
    /**
     * An id field for DB identification, automatically generated by db
     * @see Id
     * @see GeneratedValue
     * */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    Integer id;
    /**
     * Field for saving invite data
     * */
    String identify;
    /**
     * Simple invite constructor for saving and creating a new invite object
     * for noargs
     * @see NoArgsConstructor
     * */
    Invite(String identify){
        this.identify = identify;
    }

}
